### ISSUE TITLE
Failed to read artifact descriptor for de.fatalix:codmirror-addon:jar:1.2.1

### ISSUE THREAD

**Issue by fredy2015** [felixhusse/codemirror-addon#7]
Hi,

I have got the message "Failed to read artifact descriptor for de.fatalix:codmirror-addon:jar:1.2.1" when I add the dependency to my pom file. Could you fix the issue.
Thanks

Regards

Fred

**Comment by felixhusse** [comment]
problem should be solved now. Thanks for your feedback.
For a new release check here: https://vaadin.com/directory#!addon/codemirror-add-on
